title: OKUNGBENI DICKSON
logo: /assets/image/headshot_circle.png
descrition: PROFICIENT IN
           + DATA CLEANING USING SQL, R AND EXCEL
           + DATA ANALYSIS AND MANIPULATION USING SQL, R, EXCEL, POWER BI 
           + DATA VISUALISATION USING TABLEAU, R, POWER BI AND EXCEL. 
           + USAGE OF POWER QUERRY IN EXCEL AND POWER BI 
           + STORT TELLING USING TABLEAU     
show_download: true
theme: jekyLl-theme-minimal
